$$ Numpy $$

### ```Introduction to Numpy```

- Numpy is a linear algebra library, it is incredible fast works great on numerical computations.

- Numpy arrays comes in two ways: 1. Vectors
                                  2. Matrices

- Vectors are strictly 1-d arrays and matrices are 2-d arrays. Matices can still have only row or columns


#To install
!pip install numpy

In [2]:
#To import numpy library for our numerical computations.
import numpy as np

##### Numpy Arrays

In [5]:
#casting list item to numpy array.

#list
lst = [1,2,3]

#ccasting using np.array
arr = np.array(lst)
arr

array([1, 2, 3])

In [ ]:
#Type of the variable we cast.
print(type(arr))

In [6]:
#We are creating a nexted list and we convert it to 2D array with np.array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
print(my_mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
#Converting to array it will result in 2D matrice
arr_mat = np.array(my_mat)
arr_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

```py
np.arange() - It result in generate a value range mentioned from start from end. exclusive of end value.

#Syntax:
- np.arange(start,stop,step)
```

In [8]:
#To create a range of values
var1 = np.arange(1,10)
print(var1)

var2 = np.arange(1,10,2)
print(var2)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [9]:
#To get all zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
#To get all ones we have inbuilt function of ones
np.ones(3)

array([1., 1., 1.])

- You might aware that we go decimal values of the above code use dtype=int

In [ ]:
np.ones(3,dtype=int) #1D array

array([1, 1, 1])

- Suppose if you need matrice we can give using tuple, where one will be number of rows and other will be no of columns

In [ ]:
#we are taking 2x3 matrix with only integer values of one
np.ones((2,3),dtype=int)

# 2 is the row
# 3 is the column

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#linspace() - to get evenly spaced values from range specified based on step. It will result in 1D array.

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
#Identical matrix - A matrix havng same dimensions and equal to one another.

np.eye(4)  #2D array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#For random values uniformly distributed.
np.random.rand(5) #1D array

array([0.52479248, 0.67235414, 0.35180862, 0.02234995, 0.32796927])

In [23]:
#For random values in 2D array
np.random.rand(2,3)

array([[0.98844454, 0.85830213, 0.04492952],
       [0.09346032, 0.32336739, 0.19915882]])

In [27]:
#For random value from a standard normal or gausian distribution.
np.random.randn(4) #1D
np.random.randn(2,3) #2D


array([[-0.38505865,  0.58924067,  0.58843066],
       [ 0.73551443, -0.19865101,  0.44038359]])

In [ ]:
#To reshape the array. It will result an error if it not full the complete matrix with our dimensions. Ex if 2x2 means all four should be filled or else it will be an error.

arr = np.arange(25)
arr.reshape(5,5)   #5x5=25 elements need to fit in our matrix.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
#To fetch maximum value
arr.max()

np.int64(24)

In [43]:
#To fetch the minimum value
arr.min()

np.int64(0)

In [46]:
#to find the index of the max and min value
print(arr)

print(arr.argmax()) #maximum index
print(arr.argmin()) #minimum index

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
24
0


In [47]:
#To find shape of the array
arr.shape

(25,)

In [48]:
#To find the datatype of the variable
arr.dtype

dtype('int64')