$$ Numpy$$

```Indexing & Selection```

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#To get an item from the array using index value.
arr[8]

np.int64(8)

In [5]:
#To get items from the array use slice notation 
arr[2:7] #Exclusive of 7 position

array([2, 3, 4, 5, 6])

In [6]:
#slicing
arr[:6] #until position 6 from starting

array([0, 1, 2, 3, 4, 5])

In [7]:
 #starting from 6 position to end
arr[6:]

array([ 6,  7,  8,  9, 10])

In [ ]:
#Broadcasting
arr[0:3] = 25
arr #it will assign the range with assigned value where it replaces the existing value with new value.

array([25, 25, 25,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#This will fetch everything in the array
arr[:]

array([25, 25, 25,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:]  = 23
slice_of_arr

#This is just a view of the array but if will affect the orignial array as shown in below

array([23, 23, 23, 23, 23, 23])

In [ ]:
arr
#We did the selection from arr with what we need and we assigned with new value for a view it has not copied to new array, which got effected to original array. To avoid memory issue for a large array.

array([23, 23, 23, 23, 23, 23,  6,  7,  8,  9, 10])

In [13]:
#To avoid above issue we use copy
arr_copy = arr.copy()
arr_copy

array([23, 23, 23, 23, 23, 23,  6,  7,  8,  9, 10])

In [14]:
#If we do any broadcasting it will affect only the new one not the original array.
arr_copy[:] = 1
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Note: If you slice of array and assign a variable it will just take the view but not copy the array.

```2D Array Computations```

In [15]:
#Creation of 2D array
array_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#To fetch the element 5
array_2d[(0,0)] #using tuple method
array_2d[0][0] #

np.int64(5)

In [20]:
#To get entire 1st row
array_2d[1]

array([20, 25, 30])

In [24]:
#To get 40
array_2d[2][1]

#or use comma stating [row,column]
array_2d[2,1]

np.int64(40)

In [25]:
#To fetch only right side of to rows data
array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

##### Conditional Selection

In [26]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
#It will return boolean value True/False based on condition matching.
bool_arr = arr  > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [32]:
#It will return the values that are True to our condition.
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [33]:
#Conditional selection.
arr[arr>5]

array([ 6,  7,  8,  9, 10])

#### ```Example```

In [ ]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
#Fetch 22,23,32,33

arr_2d[2:4,2:4]

array([[22, 23],
       [32, 33]])