$$ Numpy Operations$$

```Numpy Operations```
- Array with array
- Array with scalars
- Universal Array Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

```Array with Array```

In [6]:
#array + array
#This will not combine the two array as list do it actually add with item + item
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#Muliplication of array x array.
arr * arr

#If you take a look we can see that it is calculating on orginal data but not on the previous calculated values from above tab.

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

```Scalar Operations```
- To performing mathematical operations between a single value (a scalar) and an array, where the operation is applied element-wise to every component of the array.

In [8]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [ ]:
arr / arr
#In general it should give division by zero error but in numpy it show runtimeWarning error and provide a "Nan" element as result.

C:\Users\raksh\AppData\Local\Temp\ipykernel_17916\2360862367.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#While 1 divided by arr gives an "inf" - infinite value as reult with warning sign.
1 / arr

C:\Users\raksh\AppData\Local\Temp\ipykernel_17916\4009398841.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [13]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

```Universal Array Functions```

In [14]:
#Square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
#max method
np.max(arr)
#arr.max()

np.int64(10)

In [16]:
#min method
np.min(arr)

np.int64(0)

In [17]:
#Sine values
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [18]:
#log function
np.log(arr)

C:\Users\raksh\AppData\Local\Temp\ipykernel_17916\1085731148.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])